### ISSUE TITLE
No italic version for operator mono

### ISSUE THREAD

**Issue by Zakarya-Netlinks** [tobiasalthoff/vscode-atom-material-theme#11]

**Comment by tobiasalthoff** [comment]
Hey @Zakarya-Netlinks ,

could you give me a little bit more context please? Thank you :-)

**Comment by Zakarya-Netlinks** [comment]
![image](https://user-images.githubusercontent.com/61266292/77904449-cf32d800-7299-11ea-9ce9-cb679edabebb.png)

**Comment by Zakarya-Netlinks** [comment]
like this theme the html attributes are in italic

**Comment by Zakarya-Netlinks** [comment]
Hey @tobiasalthoff I meant something like this
![image](https://user-images.githubusercontent.com/61266292/77905082-e4f4cd00-729a-11ea-8ac2-6183ae5aa5f5.png)

**Comment by tobiasalthoff** [comment]
Since not everyone likes Italic styles, I deliberately did not add them. But you can add the styles in your 'settings.json': 

```json
"editor.tokenColorCustomizations": {
  "textMateRules": [
    {
      "name": "Operator Mono Italics",
      "scope": [
        "entity.other.attribute-name.html",
        "entity.other.attribute-name.id.html",
        "entity.other.attribute-name.js"
      ],
      "settings": {
        "fontStyle": "italic"
      }
    }
  ]
},
```

**Comment by Zakarya-Netlinks** [comment]
Thanks
