### ISSUE TITLE
Syntax Highlighting for Vue PascalCase Components stopped working

### ISSUE THREAD

**Issue by jstiers** [tobiasalthoff/vscode-atom-material-theme#13]
Hey Tobias!

Absolutely love your theme, can't think of changing ever again.

Unfortunately the **Vue syntax highlighting for <PascalCased> components in .vue files stopped working** recently. It used to be red, but is now yellow.

Do you think you could fix that?

I'll add a screenshot for a better explanation:
![image](https://user-images.githubusercontent.com/59442292/92473803-63a34e00-f1db-11ea-9314-b5aa4732b101.png)

It used to be red, like seen here with lower-cased HTML Tags:
![image](https://user-images.githubusercontent.com/59442292/92473922-91889280-f1db-11ea-80fe-75331c9f0f40.png)

Thank you so much for this amazing theme and your hard work!

Jason

**Comment by jstiers** [comment]
I believe this to be the change that broke Atom Material Theme for Vue components. It also shows the needed modification for the theme as far as I can tell:

https://github.com/vuejs/vetur/issues/1963#issuecomment-668469351

**Edit (with potential fix):**
I added `"support.class.component.html"` below line 201 of the theme.json and it worked.
So far there are no side-effects, but I will continue to test it and report back if there is a bug.

Thank you for all the work you put in this great theme!

**Comment by tobiasalthoff** [comment]
Hey Jason,

first of all thank you for your kind words 🙂

You're right, your change fixes the issue. Does it make sense to colorize the attribute values, too? So that it is consistent with the HTML tags?

<img width="379" alt="Screenshot 2020-09-09 at 09 25 52" src="https://user-images.githubusercontent.com/17332438/92570274-f991b400-f281-11ea-8063-41ae5d57d62a.png">

**Comment by jstiers** [comment]
> Hey Jason,
> 
> first of all thank you for your kind words 🙂
> 
> You're right, your change fixes the issue. Does it make sense to colorize the attribute values, too? So that it is consistent with the HTML tags?
> 
> <img alt="Screenshot 2020-09-09 at 09 25 52" width="379" src="https://user-images.githubusercontent.com/17332438/92570274-f991b400-f281-11ea-8063-41ae5d57d62a.png">

Hey Tobias!
Thank you for your reply.

No I think other than that it's great working with the theme so far, so no other issues as far as I can tell.

Out of curiosity: what font are you using (it looks great)?

**Comment by tobiasalthoff** [comment]
Fixed with version 1.10.5 → update should be available in a few minutes!

And I use [Operator Mono](https://www.typography.com/blog/introducing-operator). It's not for free, but it's worth the money 😄

**Comment by jstiers** [comment]
> Fixed with version 1.10.5 → update should be available in a few minutes!
> 
> And I use [Operator Mono](https://www.typography.com/blog/introducing-operator). It's not for free, but it's worth the money 😄

Awesome!

Last question, haha: why are your attributes italic? Mine are regular.

**Comment by tobiasalthoff** [comment]
I don't want to force everyone to use italic styles. [But you can enable this local if you want 🙂](https://github.com/tobiasalthoff/vscode-atom-material-theme/issues/11#issuecomment-606503148)

**Comment by jstiers** [comment]
> I don't want to force everyone to use italic styles. [But you can enable this local if you want 🙂](https://github.com/tobiasalthoff/vscode-atom-material-theme/issues/11#issuecomment-606503148)

Awesome! Thanks :)

Have a great day Tobias.
