### ISSUE TITLE
python js ts code has become red (appeared in the 1.10.6)

### ISSUE THREAD

**Issue by rodmax** [tobiasalthoff/vscode-atom-material-theme#17]
Hi guys!

- After update the extension to version 1.10.6 **python, JavaScript, typescript has become RED** (shell, yaml code looks good)
- After downgrade to version `1.10.5` code started looking good again.

### `version 1.10.6`

As i can see in developer tools, red color appeared by CSS class `.mtk20`

**python**
<img src="https://user-images.githubusercontent.com/6079597/122175231-24054300-ce8c-11eb-9431-4c67771f5cfb.png" height="300px">

**JavaScript**
<img height="200px" src=https://user-images.githubusercontent.com/6079597/122175322-3c755d80-ce8c-11eb-91a0-4079f17076e8.png>

### `version 1.10.5`
NOTE: in version `1.10.5` for the same token as above, a different CSS class and corresponding color was applied: `.mtk11`

<img height="200px" src=https://user-images.githubusercontent.com/6079597/122176525-5f544180-ce8d-11eb-9db6-88043776c2c7.png>

**Comment by tobiasalthoff** [comment]
Hey! Uh, this doesn't look good. I'll take a look at it!

**Comment by tobiasalthoff** [comment]
My mistake. I had added colors for "semanticTokenColors" as a test. For a better overview in #ff0000 😅 With version 1.10.7 this is fixed for now. Update should be available in a few minutes. Sorry for the circumstances!
