### ISSUE TITLE
Theme discussion

### ISSUE THREAD

**Issue by ghost** [tobiasalthoff/vscode-atom-material-theme#3]
Hi @tobiasalthoff! Regarding on your concept of separating widget colors, we can't implement this for now because vscode doesn't supports custom theme CSS stylesheets :slightly_frowning_face: (see [vscode#459](https://github.com/Microsoft/vscode/issues/459))
Even so I'd like to have less contrast widget without colored border. What about you @tobiasalthoff? which one do you like:
**bordered..**
![2017-11-20 02-12-30](https://user-images.githubusercontent.com/26540726/32997410-6ed78008-cd98-11e7-9a9a-96c8276c0b42.png)
**or without border?**
![2017-11-20 02-14-57](https://user-images.githubusercontent.com/26540726/32997434-c726e9ce-cd98-11e7-9c99-f4c9d05329c2.png)

**Comment by tobiasalthoff** [comment]
Hey @andpawlenko ,
you're right :-( I've updated the theme and removed the border. I think it's the best solution for now. And you could use https://github.com/be5invis/vscode-custom-css to add custom css (till the VSCode team gives us more control over the theming).

**Comment by ghost** [comment]
I've tried to add some styles directly from developer tools :slightly_smiling_face: Thank you @tobiasalthoff 
Btw, I've made some changes in my forked repository:
- removed border in command prompt
- command prompt items highlighted by primary accent color #009688
- unfocused list items highlighted in dark colors
![2017-11-24 20-50-21](https://user-images.githubusercontent.com/26540726/33221856-86c54814-d15b-11e7-86c3-2fb22b5ef347.png)
see https://github.com/andpawlenko/vscode-atom-material-theme/commit/be66e3af9657a50435f806dad51b1ed8a649c630
Any more ideas?

**Comment by ghost** [comment]
Hi. What font are you using in your screenshots?

**Comment by ghost** [comment]
Hi, @saulius-spiridonas-ht. Here is my font: https://github.com/tonsky/FiraCode
