### ISSUE TITLE
[Javascript] Different color for object property

### ISSUE THREAD

**Issue by offirgolan** [tobiasalthoff/vscode-atom-material-theme#5]
Hi there,

Would it be possible to colorize JS object properties a different color? Maybe just white for better contrast / visibility?

<img width="355" alt="screen shot 2018-01-31 at 3 59 24 pm" src="https://user-images.githubusercontent.com/575938/35654059-004ec25e-06a0-11e8-8127-ee17f1ded8ed.png">

**Comment by tobiasalthoff** [comment]
Hey @offirgolan,

yeah, you're right.

I've tried the white color. But there are some cases, where this leads to another problem:

<img width="323" alt="screen shot 2018-02-05 at 16 04 58" src="https://user-images.githubusercontent.com/17332438/35811266-59e7a906-0a8e-11e8-81b6-fde6baeb4f19.png">

So I've tried some other colors. There is always one object variation, which is not 100% readable or it looks strange.

<img width="221" alt="screen shot 2018-02-05 at 16 10 23" src="https://user-images.githubusercontent.com/17332438/35811575-1a122c74-0a8f-11e8-987b-fd4f539fbbd4.png">

<img width="220" alt="screen shot 2018-02-05 at 16 11 07" src="https://user-images.githubusercontent.com/17332438/35811617-329d9454-0a8f-11e8-8a62-f877c79fb055.png">

I can darken the original color:

<img width="222" alt="screen shot 2018-02-05 at 16 58 36" src="https://user-images.githubusercontent.com/17332438/35814255-e4f63b00-0a95-11e8-922f-680774a52a65.png">

or a little bit more:

<img width="226" alt="screen shot 2018-02-05 at 16 59 54" src="https://user-images.githubusercontent.com/17332438/35814310-072166b4-0a96-11e8-978a-97b80dadd346.png">

What do you think?

**Comment by offirgolan** [comment]
@tobiasalthoff thanks for taking this up! Speaking from only personnel preference, I would go for either one of these:

![](https://user-images.githubusercontent.com/17332438/35811617-329d9454-0a8f-11e8-8a62-f877c79fb055.png)


![](https://user-images.githubusercontent.com/17332438/35811575-1a122c74-0a8f-11e8-987b-fd4f539fbbd4.png)

I think darkening the original color is still a bit hard to read and make the property names look unimportant.

**Comment by tobiasalthoff** [comment]
@offirgolan 
I've just updated the theme :-)

**Comment by offirgolan** [comment]
@tobiasalthoff that made a huge difference! Thanks for the quick follow up and release! 😄

**Comment by tonix-tuft** [comment]
How can you change the color of object properties of an arbitrary theme? Is there a VS Code setting for that?
