### ISSUE TITLE
Theme colour isn't match with your's screenshot

### ISSUE THREAD

**Issue by nijicha** [tobiasalthoff/vscode-atom-material-theme#7]
Hi, tobiasalthoff,

I tried many ways to keep my visual code with the vanilla setting.
I think It is not your's theme fault.

But finally, I can't let it match with your screenshot.

Could you please let me know how to colors it with this screenshot?

<img width="1521" alt="screen shot 2561-04-19 at 15 30 55" src="https://user-images.githubusercontent.com/12441214/38980333-c77de7c8-43e6-11e8-9d47-fe308d963207.png">

Here is mine.

<img width="1919" alt="screen shot 2561-04-19 at 15 30 35" src="https://user-images.githubusercontent.com/12441214/38980330-c6fdab30-43e6-11e8-8d02-ec54e871333b.png">

**Comment by zaccaro1980** [comment]
same issue for me

**Comment by tobiasalthoff** [comment]
Hey @nijicha ,

I've tested the theme on multiple systems (windows, mac) and can't reproduce the issue. Your settings looks right. Do you have the issue with other themes too?

I would suggest to open an issue at the vscode project: https://github.com/microsoft/vscode
