### ISSUE TITLE
Terminal does not match theme

### ISSUE THREAD

**Issue by sergio-fifthring** [tobiasalthoff/vscode-atom-material-theme#9]
The terminal colours don't match the rest of the theme's colours, especially considering that the Debug console, Output and Problems tabs do match.

Screenshot of the debug console
<img width="1440" alt="Screenshot 2019-07-11 at 11 19 59" src="https://user-images.githubusercontent.com/51951937/61043365-f83ed000-a3cd-11e9-9e02-ec25a9d52721.png">

Screenshot of the terminal
<img width="1440" alt="Screenshot 2019-07-11 at 11 20 17" src="https://user-images.githubusercontent.com/51951937/61043366-f8d76680-a3cd-11e9-84bb-b8f89ca69588.png">

**Comment by tobiasalthoff** [comment]
Fixed with version 1.6.0 :-)
